version: "3"
services:
  web:
    build: .
    ports:
      - "3100:3100"
    depends_on:
      - "meili"
    command: []

  meili:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/data.ms
