version: "3"
services:
  web:
    build: .
    ports:
      - "80:1337"
    depends_on:
      - "meili"
    command: []

  meili:
    image: getmeili/meilisearch
    ports:
      - "81:7700"
    volumes:
      - ./data.ms:/data.ms
